name: Conectar à VPN Fortinet

on:
  push:
    branches:
      - main # Mude para a branch desejada

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Add openconnect PPA
        run: |
          sudo add-apt-repository ppa:dwmw2/openconnect -y
          sudo apt-get update
          sudo apt-get install -y openconnect
  
      - name: Connect to VPN
        run: |
          echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect -u ${{ secrets.VPN_USER }} --passwd-on-stdin --protocol=fortinet ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --servercert ${{ secrets.VPN_SERVERCERT }} --background
  
      - name: Test if connected to VPN
        run: |
          ping -c4 ${{ secrets.SERVER_HOST_INSIDE_VPN }}
